### ISSUE TITLE
Update to follow Guard 2.0 changes

### ISSUE THREAD

**Issue by ezekg** [mraaroncruz/guard-uglify#5]
Getting deprecation warnings. More info is [here](https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard).

```
09:37:50 - WARN - Starting with Guard 2.0, Guard::Uglify should inherit from Guard::Plugin
> [#] instead of Guard::Guard.
> [#] Please note that the constructor signature has changed from
> [#] Guard::Guard#initialize(watchers = [], options = {}) to
> [#] Guard::Plugin#initialize(options = {}).
> [#] For more information on how to upgrade for Guard 2.0, please head over
> [#] to: https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard
> [#]
> [#] Deprecation backtrace: /Library/Ruby/Gems/2.0.0/gems/guard-2.8.2/lib/guard/ui.rb:107:in `deprecation'
> [#]    >/Library/Ruby/Gems/2.0.0/gems/guard-2.8.2/lib/guard/guard.rb:94:in `initialize'
> [#]    >/Library/Ruby/Gems/2.0.0/gems/guard-uglify-0.2.0/lib/guard/uglify.rb:9:in `initialize'
```

**Comment by mraaroncruz** [comment]
If you want to make a pull request that would be great. I don't use this project and it will probably be awhile until i fix anything.
sorry,
aaron

**Comment by ezekg** [comment]
For sure. If I create a pull request, will you update the gem?

**Comment by mraaroncruz** [comment]
Yessiree!

**Comment by ezekg** [comment]
Done. :+1:

**Comment by ezekg** [comment]
Thank ya sir.

**Comment by mraaroncruz** [comment]
I pushed to rubygems too and gave you gem push access
